title: Robin Maume # your name (or website title) here
logo: "/images/Image-modified.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A propos
  <br>
  En tant que consultant et chargé de projet SIG avec une expérience de plus de 10 ans, je suis spécialisé dans la gestion des bases de données géographiques, le big data et l'administration CRM. Ayant fondé ma micro-entreprise en 2025, je propose des services personnalisés allant de la mise en place de systèmes d'information géographique au développement d'outils d'analyses spatiales en passant par l'administration CRM et la gestion de données. En résumé, je fournis un diagnostic 360 pour répondre aux besoins complexes de mes clients.  
  Mon expertise réside dans l'analyse et la gestion des données, la géomatique et l'administration CRM, avec une maîtrise des outils payants et open source tels qu'ArcGIS, QGIS, Salesforce ou Hubspot. J'accorde une grande importance à la collaboration et à la communication avec les équipes et les partenaires, afin de garantir des solutions adaptées et efficaces pour les projets que j'accompagne.
  <br>
  Aussi...
  <br><br>
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/robin-maume/">LinkedIn</a> |
  </p>
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
